version: "3.8"

services:
  db:
    image: mysql:8.0.36
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=health-human
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_USER=healthhumanapp
      - MYSQL_PASSWORD=8lY|BSk-0DE7
    ports:
      - '3306:3306'
    networks:
      - healthhuman-network
    volumes:
      - db_app:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  application:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: healthhuman:latest
    container_name: healthhuman
    ports:
      - "30000:8000"
    networks:
      - healthhuman-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=us-east-1
      - MYSQL_DATABASE=health-human
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=healthhumanapp
      - MYSQL_PASSWORD=8lY|BSk-0DE7
    volumes:
      - db_app:/var/lib/app
    healthcheck:
      test: "curl --fail --silent localhost:8000/actuator/health | grep UP || exit 1"
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 30s

networks:
  healthhuman-network:
    driver: bridge

volumes:
  db_app:
