# Usando a imagem do Amazon Corretto para executar o aplicativo
FROM amazoncorretto:17-al2-jdk

WORKDIR /app

# Copie o JAR gerado a partir da etapa anterior para o contêiner
COPY /target/health-human-0.0.1-SNAPSHOT.jar .
COPY /target/*.properties .


# Expondo a porta que o aplicativo está ouvindo
EXPOSE 8000

# Comando para iniciar o aplicativo
ENTRYPOINT ["java", "-jar", "health-human-0.0.1-SNAPSHOT.jar"]