CREATE TABLE TB_DOCTOR (
    ID VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    ADDRESS_COMPLEMENT VARCHAR(255),
    LATITUDE FLOAT(53),
    LONGITUDE FLOAT(53),
    NAME VARCHAR(250),
    ADDRESS_NUMBER INTEGER,
    RATING INTEGER,
    SPECIALITY VARCHAR(100),
    ZIP_CODE BIGINT,
    PRIMARY KEY (ID)
) ENGINE=INNODB;