CREATE TABLE TB_SCHEDULE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_TIME DATETIME(6),
    DOCTOR_ID VARCHAR(100),
    CANCEL_JUSTIFICATION VARCHAR(255),
    PATIENT_ID VARCHAR(100),
    SCHEDULE_DATE DATETIME(6),
    SCHEDULE_STATUS TINYINT,
    UPDATED_TIME DATETIME(6),
    PRIMARY KEY (ID)
) ENGINE=INNODB;